Name:           ros-kinetic-gridmap-2d
Version:        0.4.2
Release:        0%{?dist}
Summary:        ROS gridmap_2d package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/gridmap_2d
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-devel
Requires:       ros-kinetic-nav-msgs
Requires:       ros-kinetic-rosconsole
Requires:       ros-kinetic-roscpp
BuildRequires:  opencv-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-nav-msgs
BuildRequires:  ros-kinetic-rosconsole
BuildRequires:  ros-kinetic-roscpp

%description
gridmap_2d - a simple 2D gridmap structure, based on OpenCV's cv::Mat

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Apr 19 2018 Pramuditha Aravinda <aravindadp@gmail.com> - 0.4.2-0
- Autogenerated by Bloom

