Name:           ros-kinetic-footstep-planner
Version:        0.4.2
Release:        0%{?dist}
Summary:        ROS footstep_planner package

Group:          Development/Libraries
License:        GPLv3
URL:            http://wiki.ros.org/footstep_planner
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-devel
Requires:       ros-kinetic-actionlib
Requires:       ros-kinetic-angles
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-gridmap-2d
Requires:       ros-kinetic-humanoid-nav-msgs
Requires:       ros-kinetic-map-server
Requires:       ros-kinetic-nav-msgs
Requires:       ros-kinetic-rosconsole
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-sbpl
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-visualization-msgs
BuildRequires:  opencv-devel
BuildRequires:  ros-kinetic-actionlib
BuildRequires:  ros-kinetic-angles
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-gridmap-2d
BuildRequires:  ros-kinetic-humanoid-nav-msgs
BuildRequires:  ros-kinetic-map-server
BuildRequires:  ros-kinetic-nav-msgs
BuildRequires:  ros-kinetic-rosconsole
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-sbpl
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-tf
BuildRequires:  ros-kinetic-visualization-msgs

%description
A footstep planner for humanoid / biped robots. The planner builds on SBPL and
has anytime as well as dynamic replanning capabilities. The supported planners
are: ARA*, AD*, R*. Details can be found in the following publications:
&quot;Humanoid Navigation with Dynamic Footstep Plans&quot; by J. Garimort, A.
Hornung, and M. Bennewitz; published in Proc. of the IEEE International
Conference on Robotics &amp; Automation (ICRA), 2011 Anytime Search-Based
Footstep Planning with Suboptimality Bounds by A. Hornung, A. Dornbush, M.
Likhachev, and M. Bennewitz; published in Proc. of the IEEE-RAS International
Conference on Humanoid Robots (HUMANOIDS), 2012

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Apr 19 2018 Pramuditha Aravinda <aravindadp@gmail.com> - 0.4.2-0
- Autogenerated by Bloom

